var diseaseList = ['Tuberculosis',
'rickets'
'ELECTROENCEPHALOGRAPHIC PATTERN, BETA FREQUENCY, QUANTITATIVE TRAIT LOCUS; EEGBQTL',
'LATERAL MENINGOCELE SYNDROME',
'ENDOMETRIOSIS, SUSCEPTIBILITY TO, 1',
'EOSINOPHILIA, FAMILIAL',
'MYELOPROLIFERATIVE DISORDER, CHRONIC, WITH EOSINOPHILIA',
'EPICANTHUS',
'EPIDERMOLYSIS BULLOSA SIMPLEX, LOCALIZED',
'EPIDERMOLYSIS BULLOSA SIMPLEX, GENERALIZED',
'EPIDERMOLYSIS BULLOSA SIMPLEX, OGNA TYPE',
'EPIDERMOLYSIS BULLOSA SIMPLEX WITH MOTTLED PIGMENTATION; EBS-MP',
'PHOTOPAROXYSMAL RESPONSE 1; PPR1',
'CYLINDROMATOSIS, FAMILIAL'];