var drugList = ['Valaciclovir',
'Valdecoxib',
'Lactulose',
'L-Carnitine',
'tetacycline',
'doxil',
'bextra',
'Nizatidine',
'Cinalukast',
'Penicilin G',
'Hydroxocobalamin',
'Fluticasone Propionate',
'Lisuride',
'Fluocinolone Acetonide',
'Piperazine',
'Halobetasol Propionate',
'Ocriplasmin',
'allopurinol',
'Cetuximab',
'Carfilzomib',
'Linaclotide',
'Peginesatide',
'Enzalutamide',
'tetracycline',
'Teduglutide',
'Raxibacumab',
'Formestane',
'Dimethyl fumarate',
'Trametinib',
'Radium Ra 223 Dichloride',
'Insulin, isophane',
'ALEGLITAZAR',
'Afatinib',
'Ferric Carboxymaltose'];