var targetList = ['Trifunctional purine biosynthetic protein adenosine-3',
'Mitochondrial carnitine/acylcarnitine carrier protein CACL',
'Evolved beta-galactosidase subunit alpha',
'Histamine H3 receptor',
'Metabotropic glutamate receptor 2',
'Tyrosine-protein phosphatase non-receptor type 4',
'Voltage-dependent T-type calcium channel subunit alpha-1I',
'Integrin beta-2',
'Proto-oncogene tyrosine-protein kinase ABL1',
'Mitogen-activated protein kinase 3',
'RET proto-oncogene',
'Heat shock protein HSP 90-alpha',
'Epithelial discoidin domain-containing receptor 1',
'Carnitine O-palmitoyltransferase 2 mitochondrial',
'Endoplasmin',
'Toll-like receptor 9'];